### ISSUE TITLE
This is great

### ISSUE THREAD

**Issue by chih98** [preble/SwiftToneAudioUnit#1]
this is a great piece of code and I  am very glad I came upon it! If you would like, I have made some edits to make it more versatile, I can send it to you. Have you considered uploading this as an API to cocoapods?

**Comment by preble** [comment]
@chih98 Glad you've found it useful!

If you have some changes feel free to make a fork and submit a pull request. I don't have any plans to make it available on CocoaPods or similar. I mostly put it up here on GitHub to serve as a demonstration/reference.
